source 'https://rubygems.org'
gem 'rails', '~> 5.2.4', '>= 5.2.4.5'
gem 'mysql2'
gem 'sass-rails', '~> 6.0', '>= 6.0.0'
gem 'uglifier', '>= 2.7.2'
gem 'coffee-rails', '~> 4.1.1'
gem 'jquery-rails', '>= 4.0.4'
gem 'haml', '~> 4.0.5'
gem 'nifty-utils', '~> 1.1'
gem 'nilify_blanks', '~> 1.2.0'
gem 'authie', '~> 1.1.0'
gem 'kaminari', '~> 0.17.0'
gem 'chronic', '~> 0.10.2'
gem 'dynamic_form'
gem 'activevalidators', '>= 3.3.0'
gem 'bcrypt', '~> 3.1.7'
gem 'rails_env_config', '~> 1'
gem 'chronic_duration', '~> 0.10'
gem 'datey', '~> 1.0'
gem 'nifty-attachments'
gem 'puma', '>= 4.3.12'
gem 'moonrope', '~> 2.0', '>= 2.0.0'
gem 'florrick', '~> 1.1'
gem 'delayed_job_active_record', '>= 4.1.0'
gem 'foreman'
gem 'redcarpet', '~> 3.5.1'
gem 'premailer', '~> 1.8.3'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.1', '>= 2.1.3'
  gem 'annotate', '~> 2.7.2'
  gem 'pry-rails'
end
